// Generated by CoffeeScript 1.6.3
(function() {
  (function() {
    var apiKey, dbUrl;
    dbUrl = "https://api.mongolab.com/api/1/databases/coderdojochat/collections";
    apiKey = "bWK-cL1WKkJF6yyunAhSjhszvkkTTOlM";
    return angular.module("learnlocity.api", ["ngResource"]).factory("User", function($resource) {
      var User;
      User = mongoLabResourceFactory($resource, dbUrl, "user", apiKey);
      return User;
    }).factory("Snippet", function($resource) {
      var Snippet;
      Snippet = mongoLabResourceFactory($resource, dbUrl, "snippet", apiKey);
      return Snippet;
    }).factory("Favorite", function($resource) {
      var Favorite;
      Favorite = mongoLabResourceFactory($resource, dbUrl, "favorite", apiKey);
      return Favorite;
    });
  })();

}).call(this);
